# Generated by Django 4.1.6 on 2023-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.IntegerField(max_length=35)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
