# Generated by Django 4.1.6 on 2023-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=35),
        ),
    ]
